### ISSUE TITLE
where to see the transformed characters?

### ISSUE THREAD

**Issue by bb-zhang** [Medicean/SublimeXssEncode#1]
i have installed it successfully. But I don't know how to use it? I have selected some characters in my .HTML file, however, where are the results?

thanks~

**Comment by Medicean** [comment]
1. Create a new file and type whatever you like(or open an exist file).
2. Select the word you want to encode, if you don't select nothing the plugin will encode every character.
3. Open the Command Palette(ctrl + shift + p)  and type "xssencode". You can also found it in the menu bar (Tools -> XssEncode).
4. **The result will replace the original character.**
   Hope it helps you~ @bb-zhang
